/**
 * This file was generated by Malelficus 
 */
#include <stdio.h>
 #include <elf.h>
 #include <sys/types.h> 
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>

Elf32_Ehdr elf_header = {
/* 000000 */	"\x7f\x45\x4c\x46\x1\x1\x1\x0\x0\x0\x0\x0\x0\x0\x0\x0",
/* 000010 */	2,	/* Executable file  */
/* 000012 */	3,	/* EM_386 */
/* 000014 */	1,	/* CURRENT VERSION */
/* 000018 */	0x8049060,	/* Entry point */
/* 00001c */	0x34,	/* Program Header Table file offset */
/* 000020 */	0x921c,	/* Section Header Table file offset */
/* 000024 */	0,	/* Processor Spacefic-Flags */
/* 000028 */	52,	/* ELF Header size in bytes */
/* 00002a */	32,	/* Program Header Table entry size */
/* 00002c */	8,	/* Program Header Table entry count */
/* 00002e */	40,	/* Section Header Table entry size */
/* 000030 */	27,	/* Section Header Table entry size */
/* 000032 */	26	/* Section Header string table index */
};

Elf32_Phdr pht[2] = {
{
/* 000034 */	0x6,	/* PT_PHDR */
/* 000038 */	0x34,	/* Segment file offset  */
/* 00003c */	0x8048034,	/* Segment virtual address */
/* 000040 */	0x8048034,	/* Segment physical address  */
/* 000044 */	256,	/* Segment size in file */
/* 000048 */	256,	/* Segment size in memory */
/* 00004c */	5,	/* Segment flags */
/* 000050 */	4,	/* Segment alignment */
},
{
/* 000054 */	0x3,	/* PT_INTERP */
/* 000058 */	0x134,	/* Segment file offset  */
/* 00005c */	0x8048134,	/* Segment virtual address */
/* 000060 */	0x8048134,	/* Segment physical address  */
/* 000064 */	19,	/* Segment size in file */
/* 000068 */	19,	/* Segment size in memory */
/* 00006c */	4,	/* Segment flags */
/* 000070 */	1,	/* Segment alignment */
    }};

Elf32_Shdr sht[2] = {
{
/* Section:  */
/* 00921c */	0,	/* Section name (string tbl index) */
/* 009220 */	0x0,	/* SHT_NULL */
/* 009224 */	0x0,	/* Section flags */
/* 009228 */	0x0,	/* Section virtual addr at execution */
/* 00922c */	0x0,	/* Section file offset */
/* 009230 */	0,	/* Section size in bytes */
/* 009234 */	0,	/* Link to another section */
/* 009238 */	0,	/* Additional section information */
/* 00923c */	0,	/* Section alignment  */
/* 009240 */	0,	/* Entry size if section holds table */
},
{
/* Section: .interp */
/* 009244 */	11,	/* Section name (string tbl index) */
/* 009248 */	0x1,	/* SHT_PROGBITS */
/* 00924c */	0x2,	/* Section flags */
/* 009250 */	0x8048134,	/* Section virtual addr at execution */
/* 009254 */	0x134,	/* Section file offset */
/* 009258 */	19,	/* Section size in bytes */
/* 00925c */	0,	/* Link to another section */
/* 009260 */	0,	/* Additional section information */
/* 009264 */	1,	/* Section alignment  */
/* 009268 */	0,	/* Entry size if section holds table */
}};

const unsigned char middle[] = "\x66\x69\x69\x66";


int main() { 
    int fd; 
    fd = open("malcat", O_RDWR|O_CREAT|O_TRUNC); 
    if (fd == -1) { 
        perror("Error opening file ...\n"); 
        return 1; 
    }

    if (write(fd, pht, sizeof(pht)) != sizeof(pht)) {
      perror("Error writing pht to file\n"); 
      return 1; 
    }

    if (write(fd, middle, sizeof(middle)) != sizeof(middle)) {
      perror("Error writing middle to file\n"); 
      return 1; 
    }
    
    if (write(fd, sht, sizeof(sht)) != sizeof(sht)) { 
        perror("Error writing sht to file\n"); 
        return 1; 
    } 
    printf("binary file \"malcat\" successfull created."); 
    close(fd); 
    return 0; 
} 
