#include <stdio.h>
#include <stdlib.h>
#include <sys/mman.h>

#ifdef __STDC__
extern int fileno(FILE*);
#endif

#include <malelf/defines.h>
#include <malelf/util.h>
#include <malelf/error.h>
#include <malelf/types.h>

_u8 shellcode_create(FILE* fd_o,
                     int in_size,
                     FILE* fd_i,
                     unsigned long int original_entry_point) {
  _u8 *mem, i, count = 0;

  union entry_t {
    unsigned long int int_entry;
    unsigned char char_entry[4];
  };

  union entry_t entry_point;

  entry_point.int_entry = original_entry_point;

  mem = mmap(0, in_size, PROT_READ, MAP_SHARED, fileno(fd_i), 0);
  if (mem == MAP_FAILED) {
    LOG_ERROR("Failed to map binary in memory...\n");
    return -1;
  }

  malelf_print(fd_o, "/* Generated by Malelficus */\n");

  malelf_print(fd_o, "\n\nunsigned char shellcode[] = \n");

  for (i = 0; i < in_size; i++, count++) {
    if (i == 0) {
      malelf_print(fd_o, "\t\t\t\"");
    }
    malelf_print(fd_o, "\\x%02x", mem[i]);
    if (i > 0 && ((i+1) % 10) == 0) {
      malelf_print(fd_o, "\"\n\t\t\t\"");
    } else if (i == (in_size - 1)) {
      malelf_print(fd_o, "\"\n");
    }
  }

  malelf_print(fd_o, "\n");

  malelf_print(fd_o, "\t\t\t/* mov eax, XXXX */\n");

  malelf_print(fd_o, "\t\t\t\"");
  malelf_print(fd_o, "\\xb8"); /* mov eax, XXXX */
  count++;
  malelf_print(fd_o, "\\x%02x", entry_point.char_entry[0]);
  malelf_print(fd_o, "\\x%02x", entry_point.char_entry[1]);
  malelf_print(fd_o, "\\x%02x", entry_point.char_entry[2]);
  malelf_print(fd_o, "\\x%02x", entry_point.char_entry[3]);

  malelf_print(fd_o, "\"\n");

  malelf_print(fd_o, "\t\t\t/* jmp eax */\n");
  /* jmp eax */
  malelf_print(fd_o, "\t\t\t\"\\xff\\xe0");
  
  malelf_print(fd_o, "\";\n");

  malelf_print(fd_o, "\nunsigned int patch_offset = %d;\n\n", count);

  return MALELF_SUCCESS;
}
