/**
 * This file was generated by Malelficus 
 */
#include <stdio.h>
 #include <elf.h>
 #include <sys/types.h> 
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>

Elf32_Ehdr elf_header = {
/* 000000 */	"\x7f\x45\x4c\x46\x1\x1\x1\x0\x0\x0\x0\x0\x0\x0\x0\x0",
/* 000010 */	2,	/* Executable file  */
/* 000012 */	3,	/* EM_386 */
/* 000014 */	1,	/* CURRENT VERSION */
/* 000018 */	0x8048054,	/* Entry point */
/* 00001c */	0x34,	/* Program Header Table file offset */
/* 000020 */	0x98,	/* Section Header Table file offset */
/* 000024 */	0,	/* Processor Spacefic-Flags */
/* 000028 */	52,	/* ELF Header size in bytes */
/* 00002a */	32,	/* Program Header Table entry size */
/* 00002c */	1,	/* Program Header Table entry count */
/* 00002e */	40,	/* Section Header Table entry size */
/* 000030 */	5,	/* Section Header Table entry size */
/* 000032 */	2	/* Section Header string table index */
};

Elf32_Phdr pht[1] = {
{
/* 000034 */	0x1,	/* PT_LOAD */
/* 000038 */	0x0,	/* Segment file offset  */
/* 00003c */	0x8048000,	/* Segment virtual address */
/* 000040 */	0x8048000,	/* Segment physical address  */
/* 000044 */	120,	/* Segment size in file */
/* 000048 */	120,	/* Segment size in memory */
/* 00004c */	4,	/* Segment flags */
/* 000050 */	4096,	/* Segment alignment */
}};

const unsigned char segments[] = 
[+] text:			address=84	start=84	end=120	size=36
/* Dump of section: text, offset=84 */
/* 54 */	"\x68\x41\x41\x41\x41\xba\x04\x00\x00\x00\x89\xe1\xbb\x01\x00\x00"/* exit 1 */
/* 64 */	"\x00\xb8\x04\x00\x00\x00\xcd\x80\xbb\x00\x00\x00\x00\xb8\x01\x00"/* exit 1 */
/* 74 */	"\x00\x00\xcd\x80"/* exit 2*/
[+] .shstrtab:			address=120	start=120	end=152	size=32
/* Dump of section: .shstrtab, offset=120 */
/* 78 */	"\x00\x2e\x73\x79\x6d\x74\x61\x62\x00\x2e\x73\x74\x72\x74\x61\x62"/* exit 1 */
/* 88 */	"\x00\x2e\x73\x68\x73\x74\x72\x74\x61\x62\x00\x74\x65\x78\x74\x00"/* exit 1 */
[+] .symtab:			address=152	start=352	end=464	size=112

/* padding 200 bytes */
[+] .symtab: padding 200 bytes
/* 98 */	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
/* a8 */	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
/* b8 */	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
/* c8 */	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
/* d8 */	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
/* e8 */	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
/* f8 */	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
/* 108 */	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
/* 118 */	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
/* 128 */	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
/* 138 */	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
/* 148 */	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
/* 158 */	"\x00\x00\x00\x00\x00\x00\x00\x00"

/* Dump of section: .symtab, offset=352 */
/* 160 */	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"/* exit 1 */
/* 170 */	"\x00\x00\x00\x00\x54\x80\x04\x08\x00\x00\x00\x00\x03\x00\x01\x00"/* exit 1 */
/* 180 */	"\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\xf1\xff"/* exit 1 */
/* 190 */	"\x0e\x00\x00\x00\x54\x80\x04\x08\x00\x00\x00\x00\x10\x00\x01\x00"/* exit 1 */
/* 1a0 */	"\x15\x00\x00\x00\x78\x90\x04\x08\x00\x00\x00\x00\x10\x00\xf1\xff"/* exit 1 */
/* 1b0 */	"\x21\x00\x00\x00\x78\x90\x04\x08\x00\x00\x00\x00\x10\x00\xf1\xff"/* exit 1 */
/* 1c0 */	"\x28\x00\x00\x00\x78\x90\x04\x08\x00\x00\x00\x00\x10\x00\xf1\xff"/* exit 1 */
[+] .strtab:			address=464	start=464	end=509	size=45
/* Dump of section: .strtab, offset=464 */
/* 1d0 */	"\x00\x74\x65\x73\x74\x5f\x65\x6c\x66\x2e\x61\x73\x6d\x00\x5f\x73"/* exit 1 */
/* 1e0 */	"\x74\x61\x72\x74\x00\x5f\x5f\x62\x73\x73\x5f\x73\x74\x61\x72\x74"/* exit 1 */
/* 1f0 */	"\x00\x5f\x65\x64\x61\x74\x61\x00\x5f\x65\x6e\x64\x00"/* exit 2*/
;

Elf32_Shdr sht[5] = {
{
/* Section:  */
/* 0001fd */	0,	/* Section name (string tbl index) */
/* 000201 */	0x0,	/* SHT_NULL */
/* 000205 */	0x0,	/* Section flags */
/* 000209 */	0x0,	/* Section virtual addr at execution */
/* 00020d */	0x0,	/* Section file offset */
/* 000211 */	0,	/* Section size in bytes */
/* 000215 */	0,	/* Link to another section */
/* 000219 */	0,	/* Additional section information */
/* 00021d */	0,	/* Section alignment  */
/* 000221 */	0,	/* Entry size if section holds table */
},
{
/* Section: text */
/* 000225 */	27,	/* Section name (string tbl index) */
/* 000229 */	0x1,	/* SHT_PROGBITS */
/* 00022d */	0x2,	/* Section flags */
/* 000231 */	0x8048054,	/* Section virtual addr at execution */
/* 000235 */	0x54,	/* Section file offset */
/* 000239 */	36,	/* Section size in bytes */
/* 00023d */	0,	/* Link to another section */
/* 000241 */	0,	/* Additional section information */
/* 000245 */	1,	/* Section alignment  */
/* 000249 */	0,	/* Entry size if section holds table */
},
{
/* Section: .shstrtab */
/* 00024d */	17,	/* Section name (string tbl index) */
/* 000251 */	0x3,	/* SHT_STRTAB */
/* 000255 */	0x0,	/* Section flags */
/* 000259 */	0x0,	/* Section virtual addr at execution */
/* 00025d */	0x78,	/* Section file offset */
/* 000261 */	32,	/* Section size in bytes */
/* 000265 */	0,	/* Link to another section */
/* 000269 */	0,	/* Additional section information */
/* 00026d */	1,	/* Section alignment  */
/* 000271 */	0,	/* Entry size if section holds table */
},
{
/* Section: .symtab */
/* 000275 */	1,	/* Section name (string tbl index) */
/* 000279 */	0x2,	/* SHT_SYMTAB */
/* 00027d */	0x0,	/* Section flags */
/* 000281 */	0x0,	/* Section virtual addr at execution */
/* 000285 */	0x160,	/* Section file offset */
/* 000289 */	112,	/* Section size in bytes */
/* 00028d */	4,	/* Link to another section */
/* 000291 */	3,	/* Additional section information */
/* 000295 */	4,	/* Section alignment  */
/* 000299 */	16,	/* Entry size if section holds table */
},
{
/* Section: .strtab */
/* 00029d */	9,	/* Section name (string tbl index) */
/* 0002a1 */	0x3,	/* SHT_STRTAB */
/* 0002a5 */	0x0,	/* Section flags */
/* 0002a9 */	0x0,	/* Section virtual addr at execution */
/* 0002ad */	0x1d0,	/* Section file offset */
/* 0002b1 */	45,	/* Section size in bytes */
/* 0002b5 */	0,	/* Link to another section */
/* 0002b9 */	0,	/* Additional section information */
/* 0002bd */	1,	/* Section alignment  */
/* 0002c1 */	0,	/* Entry size if section holds table */
}};


int main() { 
    int fd; 
    fd = open("file91wpio", O_RDWR|O_CREAT); 
    if (fd == -1) { 
        perror("Error opening file ...\n"); 
        return 1; 
    } 
    if (write(fd, &elf_header, sizeof(elf_header)) != sizeof (elf_header)) { 
        perror("Error writing header to file\n"); 
        return 1; 
    } 
    if (write(fd, pht, sizeof(pht)) != sizeof (pht)) { 
        perror("Error writing pht to file\n"); 
        return 1; 
    } 
    if (write(fd, segments, sizeof(segments)) != sizeof(segments)) { 
        perror("Error writing segments to file...\n"); 
        return 1; 
    } 
    if (write(fd, &sht, sizeof(sht)) != sizeof(sht)) { 
        perror("Error writing sht to file\n"); 
        return 1; 
    } 
    printf("binary file \"file91wpio\" successfull created."); 
    close(fd); 
    return 0; 
} 
