
all:
	cmake ../beangine/CMakeLists.txt
	echo "check:\n\t@echo 'No tests in this subdirectory.'" >> ../beangine/Makefile
	echo "distclean: clean\n\t@echo 'project clean.'" >> ../beangine/Makefile
	echo "install: clean\n\t@echo 'done.'" >> ../beangine/Makefile
	echo "uninstall: clean\n\t@echo 'done.'" >> ../beangine/Makefile

clean:
	@echo "done"

check:
	@echo "no tests in this subdirectory"

install:
	@echo "done"

uninstall:
	@echo "done"